#!/usr/bin/env bash
# displays:
# To infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM

function sig_killer() {
	echo "I am invincible!!!"
}

trap 'sig_killer' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
